{
  parserClass="ai.hypergraph.tidyparse.cfg.CfgInterfaceParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiImplClassSuffix="Impl"
  psiClassPrefix="CfgInterface"
  psiPackage="ai.hypergraph.tidyparse.psi"
  psiImplPackage="ai.hypergraph.tidyparse.psi.impl"

  elementTypeHolderClass="ai.hypergraph.tidyparse.psi.CfgInterfaceTypes"
  elementTypeClass="ai.hypergraph.tidyparse.psi.CfgInterfaceElementType"
  tokenTypeClass="ai.hypergraph.tidyparse.psi.CfgInterfaceTokenType"
}

cfgInterfaceFile ::= (property|COMMENT|CRLF)*

property ::= (KEY SEPARATOR VALUE) {
    pin=3
    recoverWhile="recover_property"
    mixin="ai.hypergraph.tidyparse.psi.impl.CfgInterfaceNamedElementImpl"
    implements="ai.hypergraph.tidyparse.psi.CfgInterfaceNamedElement"
//    methods=[getType getKey getValue getName setName getNameIdentifier]
}

private recover_property ::= !(KEY|SEPARATOR|COMMENT)